version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false
    user: root
    restart: on-failure

  jms:
    image: stec.jfrog.io/beerworks/vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

  zipkin:
    image: stec.jfrog.io/beerworks/openzipkin/zipkin
    ports:
      - 9411:9411

  eureka:
    image: stec.jfrog.io/beerworks/mssc-brewery-eureka
    ports:
      - 8761:8761

  config-server:
    image: stec.jfrog.io/beerworks/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure

  inventory_service:
    image: stec.jfrog.io/beerworks/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config-server
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    restart: on-failure

  invetory-failover:
    image: stec.jfrog.io/beerworks/mssc-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin

  beer-service:
    image: stec.jfrog.io/beerworks/mssc-beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config-server
      - jms
      - inventory_service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    restart: on-failure

  beer-order-service:
    image: stec.jfrog.io/beerworks/mssc-beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config-server
      - jms
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    restart: on-failure

  gateway:
    image: stec.jfrog.io/beerworks/mssc-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config-server
      - invetory-failover
      - beer-service
      - beer-order-service
      - inventory_service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    restart: on-failure
